### ISSUE TITLE
Detecting Arduino version on Ubuntu

### ISSUE THREAD

**Issue by ishakuta** [amperka/ino#1]
Hi guys, nice project! :)

Here's what I have:
- Ubuntu Linux 3.0.0-12-generic #20-Ubuntu SMP Fri Oct 7 14:56:25 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux
- Arduino, installed from ubuntu repo (sudo apt-get install arduino), package version 0022+dfsg-4ubuntu0.1

And here's what I get when I try to build some sketch:

Detecting Arduino software version ... 
Traceback (most recent call last):
  File "/usr/local/bin/ino", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ino/runner.py", line 63, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/ino/commands/build.py", line 175, in run
    self.discover()
  File "/usr/local/lib/python2.7/dist-packages/ino/commands/build.py", line 62, in discover
    self.e['arduino_lib_version'] = v = int(f.read().strip())
ValueError: invalid literal for int() with base 10: '0022ubuntu0.1'

Seems like build.py expecting something like 22 in version :) 
I don't know python, php is my primary lang now, so can't fix it quickly.

Thanks again!
P.S.: на англ. ибо мало ли кому еще пригодиться ))

**Comment by alexey-sveshnikov** [comment]
Как-то так:

``` diff
--- original/ino/commands/build.py       2011-11-24 00:56:27.698080972 +0400
+++ new/ino/commands/build.py       2011-11-24 00:57:16.734324143 +0400
@@ -58,7 +58,7 @@
         if 'arduino_lib_version' not in self.e:
             with open(self.e['version.txt']) as f:
                 print 'Detecting Arduino software version ... ',
-                self.e['arduino_lib_version'] = v = int(f.read().strip())
+                self.e['arduino_lib_version'] = v = int(re.split(r'\D', f.read().strip())[0])
                 print colorize(str(v), 'green')

         self.e.find_tool('cc', ['avr-gcc'], human_name='avr-gcc')

```
