### ISSUE TITLE
ino init does not work

### ISSUE THREAD

**Issue by dogmatic69** [amperka/ino#102]
Cloned from github and followed the readme, result: (Ubuntu 12.04)

$ ino init 
Traceback (most recent call last):
  File "/usr/local/bin/ino", line 3, in <module>
    from ino.runner import main
  File "/usr/local/lib/python2.7/dist-packages/ino/runner.py", line 23, in <module>
    import ino.commands
  File "/usr/local/lib/python2.7/dist-packages/ino/commands/**init**.py", line 5, in <module>
    from ino.commands.build import Build
  File "/usr/local/lib/python2.7/dist-packages/ino/commands/build.py", line 8, in <module>
    import jinja2
ImportError: No module named jinja2

**Comment by dogmatic69** [comment]
This fixed the problem, `sudo easy_install Jinja2`. 

Could do with adding to the docs as there are a couple other dependencies that required installing.

**Comment by aurangzaib** [comment]
``` bash
sudo bash
apt-get install arduino-core picocom
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | python
easy_install-2.7 pip && sudo pip install ino
```

**Comment by aurangzaib** [comment]
This is the canonical way of installing ino in Ubuntu ( in my case Ubuntu 13.04 )

**Comment by aurangzaib** [comment]
You dont need to install whole 'arduino' package, just 'arduino-core' is sufficient

**Comment by nkrkv** [comment]
A problem related to not installing dependencies correctly. Not a bug
