### ISSUE TITLE
Problem with 'struct' not declared in this scope.

### ISSUE THREAD

**Issue by larsenglund** [amperka/ino#107]
I'm trying to compile this project:

https://github.com/larsenglund/huset/blob/master/arduino/inotool/gateway/src/sketch.ino

which has this line:

```
void showNewCode(NewRemoteCode receivedCode) {
```

and I get this:

```
.build/uno/src/sketch.cpp:3:20: error: variable or field ‘handleNewCode’ declared void
.build/uno/src/sketch.cpp:3:20: error: ‘NewRemoteCode’ was not declared in this scope
```

but the struct is clearly declared in:

https://github.com/larsenglund/huset/blob/master/arduino/inotool/gateway/lib/NewRemoteSwitch/NewRemoteReceiver.h

What is going on here? How can I solve this?

**Comment by larsenglund** [comment]
Uhm, I tried to make a pull request for my fix for this but it ended up in a fork by mesh (https://github.com/mash/ino/pull/1) for some reason? I'm new to git :)

**Comment by nkrkv** [comment]
Fixed in 0.3.6

**Comment by evandavey** [comment]
I've just installed the latest master and I'm experiencing this issue.

**Comment by larsenglund** [comment]
Well, you can look at my original pull (https://github.com/larsenglund/ino/commit/c7c9a0dfa6f6ac3798d22e68c57ce24170f326d9) and compare that to the latest code to maybe figure out what the problem is..
