### ISSUE TITLE
Ino upload using wrong baud

### ISSUE THREAD

**Issue by mrmagooey** [amperka/ino#115]
Hi, 

Firstly, this is a great product and thank you for making it. To the issue...

Ino appears to be using the wrong baud when uploading to my atmega328 board, specifically using 115200 when the Arduino IDE is using 57600. This causes avrdude to give the error:

```
avrdude.binary: stk500_recv(): programmer is not responding
```

Going into `upload.py` and hardcoding baud to 57600 will allow the the upload to successfully complete, specifically:

```
- '-b', board['upload']['speed'],
+'-b', "57600",
```

I'm not sure where the 115200 figure comes from, happy to provide more information though (`boards.txt` appears to have the right baud, but I wasn't sure if that's where it gets it from). Ino does correctly identify the board as an atmega328 though.

NB

The baud issue I identified by moving the avrdude binary and creating a shell script in its place which prints out the avrdude call and then calls avrdude, similar to http://wiki.yobi.be/wiki/Arduino#Monitoring_avrdude_calls. 

I'm building on OSX 10.8.5, Arduino IDE is installed and working.

**Comment by nkrkv** [comment]
Didn't you forgot to specify board model while _upoading_?

`ino upload -m atmega328`

**Comment by mrmagooey** [comment]
Yes, yes I did, and I found the earlier closed issue with the same, my apologies.
