### ISSUE TITLE
Hidden ".build" Folder — Change it for "build"

### ISSUE THREAD

**Issue by rei-vilo** [amperka/ino#12]
In OS X, files and folders with a name starting by a "." are hidden.

Please change the folder name from ".build" for "build" so users can have access to it.

Thanks.

**Comment by nkrkv** [comment]
Indeed. This is true for all posix systems. Hiding was made by-design. How often would you like to access to build artifacts using regular Arduino IDE? I thought not so often basing on own experience.

Could you provide any use case?

**Comment by rei-vilo** [comment]
Bonjour Victor, 

Actually, main reasons are understanding the inner structure of Ino and debugging.

The goal is to extend Ino to chipKIT mpide and interface it with Xcode.

Diligent mpide allows to build and upload for Arduino and chipKIT platforms.

Xcode as any other standard IDE offers a much better interface than the Processing-based ones.

Makefile is cumbersome so I'm considering now Ino to be run from Xcode.

Please find attached: Arduino-mpide comparison https://docs.google.com/open?id=0B9EofSODZdANYTYyYTM1ZTAtYmI5YS00NjY4LWEwY2YtZGRhNTEwMTU4YTk2

Best regards,

**Comment by nkrkv** [comment]
Helpful doc, thanks! Will try to support chipKIT soon.

**Comment by rei-vilo** [comment]
I open a specific ticket for chipKIT extension.

This ticket is solely about the hidden ".build" folder because of the starting ".".
