### ISSUE TITLE
Trouble with simple includes

### ISSUE THREAD

**Issue by shipstar** [amperka/ino#13]
I created a bare project using `ino init`, which created a `sketch.ino` file in the src directory. When I run `ino build`, it works as expected.

I added one header file to the src directory, `test.h`, and included it in sketch.ino. When I run `ino build` again, I see the following output:

```
Searching for Board description file (boards.txt) ... /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/boards.txt
Searching for Arduino lib version file (version.txt) ... /Applications/Arduino.app/Contents/Resources/Java/lib/version.txt
Detecting Arduino software version ...  1.0 (1.0)
Searching for Arduino core library ... /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino
Searching for Arduino standard libraries ... /Applications/Arduino.app/Contents/Resources/Java/libraries
Searching for Arduino variants directory ... /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants
Searching for avr-gcc ... /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc
Searching for avr-g++ ... /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++
Searching for avr-ar ... /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar
Searching for avr-objcopy ... /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-objcopy
Scanning dependencies of src
.build/src/sketch.cpp:2:18: error: test.h: No such file or directory
make: *** [.build/src/dependencies.d] Error 1
src/sketch.cpp
.build/src/sketch.cpp:2:18: error: test.h: No such file or directory
make: *** [.build/src/sketch.o] Error 1
```

Here is my complete code (both files in the src directory), just for reference:

**sketch.ino**

``` c
#include "test.h"

void setup()
{
}

void loop()
{
}
```

**test.h**

``` c
// empty
```

**Comment by rei-vilo** [comment]
Same problem for me: library not found.

I tried two cases:
1• the library is in the sketchbook/libraries user folder,
2• the library is in the project's src sub-folder.

Both return an error.

**Comment by zenoamaro** [comment]
It seems that ino fails when parsing the `dependencies.d` file, when multiple dependencies are given in a single line:

```
sketch.o: .build/src/sketch.cpp \
    /Applications/Arduino.app/.../arduino/Arduino.h \
    /Applications/Arduino.app/.../arduino/binary.h \
    ...
    /Applications/Arduino.app/.../arduino/new.h \
    /Applications/Arduino.app/.../standard/pins_arduino.h \
    lib/SSegs/SSegs.h lib/Framebuffer/Framebuffer.h lib/Metro/Metro.h
```

The problem is that _match_ only matches the first occurence. Without changing the REs, the fix is as simple as this:

in `commands/build.py`:173

``` python
used_libs = set()
with open(output_filepath) as f:
    for line in f:
        matches = local_re.findall(line) or dist_re.findall(line)
        for match in matches:
            used_libs.add(match[0])
```

While using _findall_ is not as nice as the regular _match_ (as we lose references to named groups), it works. I'll provide a patch later.

**Comment by fabiankr** [comment]
Did anyone get includes to work correctly? The pull request doesn't work for me.

**Comment by zenoamaro** [comment]
Here is a link to a test sketch that builds: [test-sketch.zip](http://www.mediafire.com/?y1v6s8y4vo7o05f)

This is the sketch file tree:

```
test-sketch/
    lib/
        TestLib/
            TestLib.h
            TestLib.cpp
    src/
        sketch.ino
```

TestLib is simply imported as `#include <TestLib.h>`, as it will automatically be in the path.

**Comment by fabiankr** [comment]
Okay, that works fine. But what about something like this:

```
test-sketch/
    lib/
    src/
        sketch.ino
        defines.h
```

There's no way to include defines.h in sketch.ino but this build fine using the official IDE. If you can help me to get it working, it'd be awesome.

**Comment by zenoamaro** [comment]
I'm sorry, I misunderstood your problem, I thought it was the same as mine.

Well, I know the official Arduino IDE concatenates all the tabs open in the project. Perhaps ino only concatenates multiple .ino files? I'll make some tests.

Regarding #including per se: it seems that the automagic build step moves sources around. If so, then a `#define "lib.h"` would search for the file in the wrong directory. I remember having witnessed this during my initial troubles with imports.

**Comment by rei-vilo** [comment]
I'm referring to the user-developped libraries, placed in the sketchbook/libraries folder.

The sketchbook directory is declared in the Preferences pane of the Arduino IDE.

The sub-folder called `Libraries` is included in the building process _by default_.

**Comment by fabiankr** [comment]
@rei-vilo:  You need to move the user-developed libraries to the `lib` subfolder.
@zenojevski: gcc searches for the headers in the `current directory`, but I don't understand the MakeFile.jinja code well enough to make it work correctly. Somewhere the header files need to be moved to the working directory of gcc...

**Comment by fabiankr** [comment]
If you write `#include "../../src/Defines.h"` it works without problems. That means the `.h` files only need to be moved in the `.build/src/` directory like the other files.  
I don't know where ino does the copying of the files, but I will try to solve the issue now.

**Comment by fabiankr** [comment]
There is now a working fork with simple includes: https://github.com/amperka/ino/pull/20

**Comment by zenoamaro** [comment]
@fabiankr Here is a less invasive "fix" that allows importing from "src/" by adding it to the dependency scan. I've also added a few fixes and a test sketch a couple commits later.

If you could let me know if it works for your situation it'd be great.

**Comment by fabiankr** [comment]
It works like a charm. I like your solution more, thanks. :)

**Comment by zenoamaro** [comment]
@fabiankr Thanks!
