### ISSUE TITLE
error: 'INPUT_PULLUP' was not declared in this scope

### ISSUE THREAD

**Issue by lukavia** [amperka/ino#145]
INPUT_PULLUP is a standard constant just like INPUT and OUTPUT and is used in pinMode. 
Please, add it so we don't get an error when trying to compile a standard example like 
http://arduino.cc/en/Tutorial/InputPullupSerial

**Comment by translucide** [comment]
INPUT_PULLUP is defined in arduino librairies / arduino core. Ino does not define, rewrite nor provides arduino libs, it links them to your code only. Ino is only an automated build process that replaces the arduino IDE build process, but not the libs that comes with the arduino IDE. Perhaps it did not find the arduino librairies or arduino core ? Your code example compiles fine for me with latest version using Ino with the arduino core files from arduino v 1.0.5.

**Comment by lukavia** [comment]
Got it. 
It turns out I have ubunto package installed of arduino version 1.0 and that is why I get the error. 
Thank you very much.

**Comment by chrisspen** [comment]
I don't understand this resolution. I also have Arduino 1.0 installed and I'm also getting this error. Was this name introduced in 1.5? Did you fix this by upgrading to 1.5?

**Comment by lukavia** [comment]
I've actually removed the package, installed the tar from the web and linked to those libraries
