### ISSUE TITLE
Integration of Ino as a Plug-In for a Standard IDE

### ISSUE THREAD

**Issue by rei-vilo** [amperka/ino#15]
Ino provides the unique opportunity to avoid dealing with makefile.

How to integrate Ino as a plug-in for a standard IDE like NetBeans, Eclipse, ... ?

• new project
• build
• upload 
• monitor

**Comment by rei-vilo** [comment]
It seems Fabian catched the idea with [Cocoduino](https://github.com/fabiankr/)

> Cocoduino is an IDE for the Arduino platform written in native Cocoa.

**Comment by nkrkv** [comment]
Not concrete. It's looks like a problem that should be solved on IDE’s side, not on `ino`’s. If some concrete issue blocks `ino` integration with particular IDE, please open new issue with granular details.
