### ISSUE TITLE
Add support for Pro Micro

### ISSUE THREAD

**Issue by Bouni** [amperka/ino#157]
Hi,

is it possible to add support for <a href="https://www.sparkfun.com/products/12640">Arduino Pro Micro</a> boards?
I've added the Arduino addon files to my /usr/share/arduino/hardware/ folder and can compile and upload a sketch with the Arduino IDE, but inotool seems to not recognize the additional folder.

Is there a way to tell inotool to use the addon files?

**Comment by Bouni** [comment]
Hi,

i finally found a solution for my problem, its to much to write here, so i blogged about it:
http://blog.bouni.de/blog/2014/04/08/get-the-sparkfun-promicro-working-with-inotool/

**Comment by ChandlerSwift** [comment]
The link above no longer works. Here's a working link to the same. 
http://web.archive.org/web/20141021025158/http://blog.bouni.de/blog/2014/04/08/get-the-sparkfun-promicro-working-with-inotool/
