### ISSUE TITLE
Is it possible to drop Arduino IDE dependancy?

### ISSUE THREAD

**Issue by ghost** [amperka/ino#161]
I want cmd tool to install on ubuntu server and remotely control arduino board.

Can I install ino without Arduino IDE?

Or, is it possible to install Arduino IDE on server without gui?

**Comment by jminardi** [comment]
I have successfully used ino to build and upload sketches from my raspberry pi with no GUI, is this what you mean?

**Comment by wearede** [comment]
Exactly, ino homepage states arduino IDE is required, which is primarily gui based correct?

**Comment by jminardi** [comment]
You just have to install the arduino IDE (`apt-get install arduino`, IIRC) but then you can use ino without any GUI. I run it over ssh without X and everything works.

**Comment by wearede** [comment]
Thanks for the tip!

**Comment by hoosierEE** [comment]
`apt-get install arduino-core` is even more minimal; doesn't require Java.
