### ISSUE TITLE
3rd party library not compiling

### ISSUE THREAD

**Issue by fabiankr** [amperka/ino#17]
Hello,

When building a 3rd party library, what's the desired structure of the lib directory? I'm moving the required folder from ~/Arduino/libraries/ to the /lib directory, but it doesn't seem to work, because it can't find "wiring.h".

root
       -- src
         -- source files
       -- lib
         -- external libraries

Is that the correct structure? Or do I need to remove the top level directory from my external libraries so there are just the source files?

Regards,
Fabian

**Comment by rei-vilo** [comment]
Does Ino take into account the user libraries from the specific SketchBook/Libraries folder?

**Comment by fabiankr** [comment]
No, I don't think so. I moved all necessary libraries to the lib directory and it works. It was just one particular library that did not compile correctly. But it even fails with the official IDE, so no problem here.

**Comment by nkrkv** [comment]
Taking $sketchbook/libraries into account is in plans

**Comment by rei-vilo** [comment]
Great!

**Comment by efatsi** [comment]
Re "Taking $sketchbook/libraries into account is in plans". This would be an awesome feature!
