### ISSUE TITLE
inorc

### ISSUE THREAD

**Issue by florintanasa** [amperka/ino#21]
Hello,
I use gentoo linux. In funtoo or gentoo is very dificult to install avr toolset and arduino from source, but I did with avr-libc-1.8.0.
With this version I have errors compilation in arduino.
Then I downloaded the arduino-0023 from arduino.cc site and I got the toolset from wiring (tools directory) and I put the toolset in arduino-0023 in hardware folder.
The I modified  Sconstroct from arscons with new toolset path and I make compilation without errors.
You can put in inorc this posibility to choise the toolset path ?

**Comment by nkrkv** [comment]
Well, maybe. I'll think about it. But for now, could you put tool set you've got to /usr/local/bin? After all you have working AVR compiler, why not to share it in your system?

If you don't want to do that, there is one more workaround. Add arduino-0023 hardware tools directory to your `PATH` once before using ino:

```
export PATH=/path/to/avr/tools:$PATH
```

**Comment by florintanasa** [comment]
Thanks for your idea.
But for this moment I wish to use two toolset.

**Comment by nkrkv** [comment]
Fixed in 0.3.6
