### ISSUE TITLE
Cant upload to Arduino DUE

### ISSUE THREAD

**Issue by JanezCim** [amperka/ino#220]
Hello.

I'm just asking if anyone got to uploading a sketch to Arduino DUE with inotool. When I want to do it I get the error:

avrdude: stk500_getsync(): not in sync: resp=0x66
avrdude done.  Thank you.

This, I think, is because DUE uploading is only going to work with Arduino 1.5.X and later versions. Is there any update in the plan?

Thank you for any answer!

**Comment by mathvav** [comment]
Seems to be a duplicate: https://github.com/amperka/ino/issues/183
