### ISSUE TITLE
MCU change -> no rebuild

### ISSUE THREAD

**Issue by ponty** [amperka/ino#3]
Rebuild is not started if I change the MCU:

```
$ ino build -m mini 
...
$ ino build -m mega 
make: Nothing to be done for `all'.
make: Nothing to be done for `all'.
```

**Comment by nkrkv** [comment]
Thanks!

This is because make doesn't rebuild when Makefile itself changes. Will look for most elegant solution.

**Comment by pfalcon** [comment]
Up!
