### ISSUE TITLE
sudo pip install ino misses argparse on Ubuntu 10.04

### ISSUE THREAD

**Issue by rpavlik** [amperka/ino#33]
I'm running Ubuntu 10.04 x64, and after installing python-pip and running `sudo pip install ino` (wihch claimed deps were satisfied), running `ino --help` produced the error: 

```

[ rpavlik@articuno ino ] $ ino --help
Traceback (most recent call last):
  File "/usr/local/bin/ino", line 3, in <module>
    from ino.runner import main
  File "/usr/local/lib/python2.6/dist-packages/ino/runner.py", line 20, in <module>
    import argparse
ImportError: No module named argparse
```

Installing `python-argparse` with apt-get solved the issue, but it seems like this dep might need to be added to the python package.

**Comment by nkrkv** [comment]
Well, `argparse` is a standard package since Python 2.7. So it should be mentioned if system Python version is 2.6 or lower.

Thanks for reporting.
