### ISSUE TITLE
stdlib.h

### ISSUE THREAD

**Issue by mal10c** [amperka/ino#34]
I'm creating the example blink project and trying to build it using: "ino build"

I'm getting a fatal error while trying to locate stdlib.h - but I wrote a quick c program and included the stdlib.h and the c program compiled fine.  I pasted the ino build information below:

bash-4.1$ ino build
Searching for Board description file (boards.txt) ... /usr/local/share/arduino/hardware/arduino/boards.txt
Searching for Arduino lib version file (version.txt) ... /usr/local/share/arduino/lib/version.txt
Detecting Arduino software version ...  1.0 (1.0.1)
Searching for Arduino core library ... /usr/local/share/arduino/hardware/arduino/cores/arduino
Searching for Arduino standard libraries ... /usr/local/share/arduino/libraries
Searching for Arduino variants directory ... /usr/local/share/arduino/hardware/arduino/variants
Searching for avr-gcc ... /usr/bin/avr-gcc
Searching for avr-g++ ... /usr/bin/avr-g++
Searching for avr-ar ... /usr/bin/avr-ar
Searching for avr-objcopy ... /usr/bin/avr-objcopy
src/sketch.ino
Searching for Arduino lib version file (version.txt) ... /usr/local/share/arduino/lib/version.txt
Detecting Arduino software version ...  1.0 (1.0.1)
Scanning dependencies of src
/usr/local/share/arduino/hardware/arduino/cores/arduino/WMath.cpp:27:22: fatal error: stdlib.h: No such file or directory
compilation terminated.
make: **\* [.build/arduino/WMath.d] Error 1
Make failed with code 2

**Comment by nkrkv** [comment]
Thanks for the report. What the platform you're on? What's the version of AVR GCC?
