### ISSUE TITLE
Python 3.2 dosn't work

### ISSUE THREAD

**Issue by alexkutsan** [amperka/ino#36]
A have instaled ino. Now i try to run it, and i get error 

[alex@dhcppc0 ino]$ ino --help
Traceback (most recent call last):
  File "/usr/local/bin/ino", line 3, in <module>
    from ino.runner import main
  File "/usr/lib/python3.2/site-packages/ino-0.3.3-py3.2.egg/ino/runner.py", line 65
    print colorize(str(exc), 'red')
                 ^
SyntaxError: invalid syntax

I understand, that it is becouse of puthon2 syntax. But how to fix it?

**Comment by nkrkv** [comment]
This should be written as:

print(colorize(str(exc), 'red'))

Note the brackets. I guess there would be very many incompatibilities. For now it is easier to just get Python 2.x

**Comment by alexkutsan** [comment]
Yes, thats right. But how can i tell ino to use python 2?

alias python='python2' doesn't work

**Comment by nkrkv** [comment]
How did you installed ino? With `pip install`?

In that case `pip` had to belong to python2. It depends on your distro, you could have pip2 or something like this.

**Comment by alexkutsan** [comment]
No, i instaled it by 
make install {dosn't work}
then 
python setun.py install{works} .

But i solved this problem. I changed 
#!/usr/bin/python  ->   #!/usr/bin/python2 
in /usr/local/bin/ino
If you will change there, it would be nice. :-) 
P.S. Sorry for my english.

**Comment by nkrkv** [comment]
No problems. My English is bad as well :)

The right solution is to make it work in any python. Simply changing it to python2 will cause problems on many distros.
