### ISSUE TITLE
upload faild, wrong build

### ISSUE THREAD

**Issue by alexkutsan** [amperka/ino#37]
first:

``` bash
[alex@dhcppc0 first]$ ino upload
Guessing serial port ... /dev/ttyACM0

avrdude: Can't find programmer id "arduino"
```

but 

``` bash
[alex@dhcppc0 first]$ avrdude -c arduino
avrdude: No AVR part has been specified, use "-p Part"
```

I dont understant why. 
So i did 

``` bash
[alex@dhcppc0 first]$ cd .build/
avrdude -V -F -c arduino -p atmega328p -P /dev/ttyACM0 -U flash:w:firmware.hex 
```

It's uploaded. But code(Blink) Does not work. LED is lit and not flashing. I know, that it is posible, if compilation was under another platform. So i did 

ino build -m atmega328

But a have got the same result.

**Comment by nkrkv** [comment]
Can I guess you've got Arch Linux? What is the version of AVR-GCC?
`$ avr-gcc -v`

**Comment by alexkutsan** [comment]
``` bash

[alex@dhcppc0 first]$ avr-gcc -v
Using built-in specs.
COLLECT_GCC=avr-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/avr/4.7.1/lto-wrapper
Target: avr
Configured with: /build/src/gcc-4.7.1/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-languages=c,c++ --disable-libssp --disable-nls --target=avr --with-as=/usr/bin/avr-as --with-ld=/usr/bin/avr-ld --with-gnu-as --with-gnu-ld
Thread model: single
gcc version 4.7.1 (GCC) 
```

I has reinsaled arduino.  And got mistake 

``` bash
[alex@dhcppc0 first]$ ino build
make: *** Нет правила для сборки цели `/usr/share/arduino/hardware/arduino/cores/arduino/pins_arduino.h', требуемой для `.build/src/sketch.d'.  Останов.
Make failed with code 2
```

Upload is works( but code doesn't)
Then i removed  arduiono. Then i instaled arduino-cli from https://github.com/mdevaev/arduino-cli to /usr/share/arduino with `make install` ( Eror with upload) . Then I downloaded oficial arduino from git. Then i copyed all from git-arduino to arduino instaled from arduino-cli( build works upload doesn't). but `avrdude -V -F -c arduino -p atmega328p -P /dev/ttyACM0 -U flash:w:firmware.hex` works, but incorect( LED doesn't blink)

**Comment by nkrkv** [comment]
Its strange. `pins_arduino.h` belong to old Arduino Software 0.x. Can't figure out how could it be indirectly included in your Blink example. Will investigate this issue.

**Comment by alexkutsan** [comment]
Sorry. All is ok. I reinstaled arduino again. And after `ino clean`, and chanke sketch code from threre http://inotool.org/quickstart to ofocial Blink ( I dont know, what was the stumbling block). All works. Sanks :-)
