### ISSUE TITLE
.build/arduino/WInterrupts.d:1: *** missing separator

### ISSUE THREAD

**Issue by chriskonstad** [amperka/ino#39]
On OSX 10.8, I get the "Make failed with code 2" error because ".build/arduino/WInterrupts.d:1: **\* missing separator.  Stop."  I tried creating a test project "ino init -t blink" and then running "ino build -m atmega328", but I got this error.

**Comment by nkrkv** [comment]
Could you provide a listing of: `.build/arduino/WInterrupts.d`?

**Comment by chriskonstad** [comment]
``` makefile
-n .build/arduino/WInterrupts.d .build/arduino/
WInterrupts.o:  \
 /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WInterrupts.c \
  /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_private.h \
  /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Arduino.h \
  /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/binary.h \
  /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/standard/pins_arduino.h
```

**Comment by nkrkv** [comment]
Well, it's a known bug on MacOS that was fixed in master repo. Would you update from repo instead of installing from PyPi?

**Comment by chriskonstad** [comment]
Okay.  Thanks for the help!  Sorry I missed those closed issues.
