### ISSUE TITLE
Using ino on Mac OS X — Report

### ISSUE THREAD

**Issue by rei-vilo** [amperka/ino#4]
I've been trying ino _amperka-ino-756384f_ on OS X 10.7.2.

I'm running Mpide.app instead of Arduino.app because I'm using a chipKIT UNO32 board. Mpide is based on Arduino 0022 but can address both ATMega platform / Arduino boards and PIC32 platform / chipKIT boards.

Main problem resides on the _folders_.
- Arduino.app is a folder so we need to specify where the looked after directories are within

=> Edit environment.py
=> Add to arduino_dist_dir_guesses = [
        '/Applications/Mpide.app/Contents/Resources/Java', 
**FIXED**
- The file with the version number actually has a text

=> Edit /Applications/Mpide.app/Contents/Resources/Java/lib/version.txt
=> Change 0022-macosx-20110822 for 22
**FIXED**
- The avr- tools are within the Mpide.app folder and not in a separate because there's no need of specific drivers on OS X.

=> copy/create aliases on /usr/local/bin to /Applications/Mpide.app/Contents/Resources/Java/hardware/tools/avr/bin
**FIXED** for some avr- tools
- But this doesn't work well and shows an error when looking for avr-g++

=> Edit environment.py
=> Add to arduino_dist_dir_guesses = [
        '/Applications/Mpide.app/Contents/Resources/Java/hardware/tools/avr',
**FAIL**

Best solution would be to add a _configuration file_ so the user could enter all those directories.

---

**File Log**
_Using INO on Mac OS X — amperka-ino-756384f_

macbook:ino_test user$ ino build -d /Applications/Mpide.app/Contents/Resources/Java 
Searching for Board description file (boards.txt) ... /Applications/Mpide.app/Contents/Resources/Java/hardware/arduino/boards.txt
Searching for Arduino core library ... /Applications/Mpide.app/Contents/Resources/Java/hardware/arduino/cores/arduino
Searching for Arduino standard libraries ... /Applications/Mpide.app/Contents/Resources/Java/libraries
Searching for Arduino lib version file (version.txt) ... /Applications/Mpide.app/Contents/Resources/Java/lib/version.txt
Detecting Arduino software version ... 
Traceback (most recent call last):
  File "/usr/local/bin/ino", line 5, in <module>
    pkg_resources.run_script('ino==0.1.11', 'ino')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 489, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1207, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/ino-0.1.11-py2.7.egg/EGG-INFO/scripts/ino", line 6, in <module>
    main()
  File "/Library/Python/2.7/site-packages/ino-0.1.11-py2.7.egg/ino/runner.py", line 63, in main
    args.func(args)
  File "/Library/Python/2.7/site-packages/ino-0.1.11-py2.7.egg/ino/commands/build.py", line 174, in run
    self.discover()
  File "/Library/Python/2.7/site-packages/ino-0.1.11-py2.7.egg/ino/commands/build.py", line 61, in discover
    self.e['arduino_lib_version'] = v = int(f.read().strip())
ValueError: invalid literal for int() with base 10: '0022-macosx-20110822'

=> Edit environment.py
=> Add to arduino_dist_dir_guesses = [
        '/Applications/Mpide.app/Contents/Resources/Java', 

=> Edit /Applications/Mpide.app/Contents/Resources/Java/lib/version.txt
=> Change 0022-macosx-20110822 for 22

...
macbook:ino_test user$ ino build -d /Applications/Mpide.app/Contents/Resources/Java 
Detecting Arduino software version ...  22
Searching for avr-gcc ... FAILED
avr-gcc not found. Searched in following places: 
- /opt/local/bin
- /opt/local/sbin
- /opt/local/bin
- /opt/local/sbin
- /opt/local/bin
- /opt/local/sbin
- /opt/local/bin
- /opt/local/sbin
- /opt/local/bin
- /opt/local/sbin
- /usr/bin
- /bin
- /usr/sbin
- /sbin
- /usr/local/bin
- /usr/X11/bin
- /usr/local/git/bin
- /opt/local/bin

=> Edit environment.py
=> Add to arduino_dist_dir_guesses = [
        '/Applications/Mpide.app/Contents/Resources/Java/hardware/tools/avr',

macbook:ino_test user$ ino build
Searching for avr-objcopy ... /usr/local/bin/avr-objcopy
Scanning dependencies of src
/bin/sh: /usr/local/bin/avr-gcc: cannot execute binary file
make: **\* [.build/src/dependencies.d] Error 126
src/sketch.cpp
make: /usr/local/bin/avr-g++: No such file or directory
make: **\* [.build/src/sketch.o] Error 1
macbook:ino_test user$ ino build
make: Nothing to be done for `all'.
src/sketch.cpp
/usr/local/bin/avr-g++: /usr/local/bin/avr-g++: cannot execute binary file
make: **\* [.build/src/sketch.o] Error 126
macbook:ino_test user$ 

=> ?

**Comment by rei-vilo** [comment]
Let me know when there's a new release to be tested on a Mac based on my previous report.

**Comment by nkrkv** [comment]
Ino got support of MacOS
