### ISSUE TITLE
Make failed (code 2) Linux (poisoned "SIG_USART*_RECV")

### ISSUE THREAD

**Issue by ZachMassia** [amperka/ino#40]
ino build -v
arduino/HardwareSerial.cpp
/usr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/LiquidCrystal -fno-exceptions  -o .build/arduino/HardwareSerial.o -c /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
/usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp:91:41: error: attempt to use poisoned "SIG_USART0_RECV"
/usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp:101:15: error: attempt to use poisoned "SIG_USART0_RECV"
/usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp:132:15: error: attempt to use poisoned "SIG_USART1_RECV"
/usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp:145:15: error: attempt to use poisoned "SIG_USART2_RECV"
/usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp:158:15: error: attempt to use poisoned "SIG_USART3_RECV"
make: **\* [.build/arduino/HardwareSerial.o] Error 1
Make failed with code 2

Using the Arduino IDE 1.0.1 the code compiles with no errors. I'm using an Arduino Mega ADK.

I'm on Arch Linux with the following software versions:
        avr-binutils 2.22-3
        avr-gcc 4.7.1-2
        avr-libc 1.8.0-4
        avrdude 5.11.1-1

**Comment by nkrkv** [comment]
I'm on Arch too. And seems like edge versions of avr gcc are not very friendly to Arduino codebase. In next version gcc bundled with IDE will be preferred. For now you could replace a line 72 in `ino/commands/build.py` from:

`system_wide = platform.system() == 'Linux'`

to

`system_wide = False`

To force bundled toolset usage.

Thanks for report!

**Comment by ZachMassia** [comment]
Thanks for the reply.

I changed the line, and even after a reboot the error is still the same.

It still seems to be calling /usr/bin/avr-g++ as well.

*EDIT:
Seems to work fine now, I made a fresh directory and it compiled without errors.

Thanks again.

**Comment by nkrkv** [comment]
Yeah, it was a cache that has had to be purged with `ino clean`

**Comment by rjehangir** [comment]
I know this is an old issue, but this can also be resolved by adding a flag during compilation:

 ino build --cxxflags="-D__AVR_LIBC_DEPRECATED_ENABLE__"
