### ISSUE TITLE
`ino build' fails on Mountain Lion [patch]

### ISSUE THREAD

**Issue by jdiez17** [amperka/ino#41]
Hello, I noticed that building a simple blink project fails on Mountain Lion using the last revision from Git.

I would get an error like this: 

```
$ ino build
.build/arduino/WInterrupts.d:1: *** missing separator.  Stop.
Make failed with code 2
```

After tinkering around a bit, I found that ino builds perfectly adding a slash to each .d file. Below is the patch I applied to the tree, and it works fine for me. 

```
 diff --git a/ino/make/Makefile.deps.jinja b/ino/make/Makefile.deps.jinja
index 4ce5e6e..292f316 100644
--- a/ino/make/Makefile.deps.jinja
+++ b/ino/make/Makefile.deps.jinja
@@ -14,7 +14,7 @@
 {% endif %}

 {% for source, target in cpp.items() %}
-{{ target.path }} : {{ source.path }}
+{{ target.path }} : {{ source.path }} {{ slash }}
        @mkdir -p {{ target.path|dirname }}
        {{v}}{{ e.cc }} {{ e.cflags }} {{ inc_flags }} {{ iquote(source) }} -MM $^ > $@
        {# prepend build path to a target in the generated file and 
```

**Comment by nkrkv** [comment]
Thanks for the report. It's a known issue that is fixed in master. See https://github.com/amperka/ino/issues/39

**Comment by jdiez17** [comment]
Hey, thanks for the quick answer.

Unfortunately, that doesn't seem to work on Mountain Lion, but adding a slash to the definition seems to do it.
