### ISSUE TITLE
ino list-models fails

### ISSUE THREAD

**Issue by poulsbo** [amperka/ino#42]
I have installed ino in its own virtualenv using pip. When I run 'list-models' it fails.

$ ino list-models
Searching for Board description file (boards.txt) ... FAILED
Board description file (boards.txt) not found. Searched in following places: 
- /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino
- /usr/local/share/arduino/hardware/arduino
- /usr/share/arduino/hardware/arduino

**Comment by nkrkv** [comment]
You should have Arduino IDE installed as well. It is searched on paths listed. If you've installed IDE to another location, use `--arduino-dist` arg on command line.

**Comment by bicepjai** [comment]
i still face the same issue on 1.5.5 beta on mac 10.9.1

**Comment by sujal** [comment]
that's because the file isn't in the old directory. The file is now in /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/boards.txt

Any chance for a fix?

**Comment by liquiddandruff** [comment]
Ino still searches for the boards.txt in the wrong place. Why isn't there a fix for this yet?

**Comment by qguv** [comment]
I'm having the same issue on OS X 10.11.
