### ISSUE TITLE
Using ino with avr-libc only

### ISSUE THREAD

**Issue by rsobik** [amperka/ino#54]
I'm asking myself if it is possible to use `ino` without the Arduino libraries. `ino` is a great tool for building, uploading and communicating with microcontrollers. I would love it, if it would be possible to ditch the Arduino components for some projects, where I am very size constrained.

If it is not possible at the moment and there is interest in such a feature I could try to implement it (with some help possibly).

**Comment by nkrkv** [comment]
Hm… It could be a good idea. Will think about it. For now `ino` is Arduino-only.

Raw micro controllers are more advanced beasts so I thought their developers feel more comfortable with traditional `make` and friends. However maybe I'm not right with this point of view.

**Comment by rsobik** [comment]
I started playing around with cmake and came across https://github.com/queezythegreat/arduino-cmake, which uses cmake to build arduino projects. It is very flexible and allows non-arduino-builds, which is exactly what I was looking for.
