### ISSUE TITLE
Writing to the board bug.

### ISSUE THREAD

**Issue by defbug** [amperka/ino#61]
When I upload blink or empty sketch that comes with inotools I got no problem it uploaded without fail but when i modify the sketch like in the tutorial in inotools to use serial. I got this problem.

This is the code on inotools that I am uploading.

void setup()
{
    Serial.begin(9600);
}

void loop()
{
    Serial.println(millis());
    delay(1000);
}

Now when i type.

ino build - no problem
ino upload -m uno -p /dev/ttyACM0

This is what i get.

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f
avrdude: reading input file ".build/uno/firmware.hex"
avrdude: writing flash (1084 bytes):

Writing | ##############################                     | 59% 0.12savrdude: stk500_recv(): programmer is not responding

Why is it doing that? using the sketch that comes with inotools works like blink and empty but when i created a new sketch or modify blink or empty sketch i get the error above?

**Comment by nkrkv** [comment]
Hmmm… Stall on 59%? Quite strange. Did you use any config files? I mean are you sure that you build for Uno and upload to Uno too. I see explicit `-m` for upload, but see no one for build.

**Comment by defbug** [comment]
Yes i did try that but still I can't upload to arduino. Here's what i get when i upload the blink sketch that comes with inotools.

ino init -t blink
ino build -m uno
ino upload -m uno -p /dev/ttyACM0

Here's what i get.

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f
avrdude: reading input file ".build/uno/firmware.hex"
avrdude: writing flash (1076 bytes):

Writing | ################################################## | 100% 0.21s

avrdude: 1076 bytes of flash written
avrdude: verifying flash memory against .build/uno/firmware.hex:
avrdude: load data flash data from input file .build/uno/firmware.hex:
avrdude: input file .build/uno/firmware.hex contains 1076 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.18s

avrdude: verifying ...
avrdude: 1076 bytes of flash verified

avrdude: safemode: Fuses OK

avrdude done.  Thank you.

It upload successfully why is it doing that?.. but when i try to modify the blink sketch it stalls at 59%?

Also by the way Im using kvm.. On kvm host arduino is detected as /dev/ttyACM0 now I pass that port to a guest linux vm. Now on linux vm i can see /dev/ttyACM0. but when tryting to upload i get this issue. Thanks

**Comment by nkrkv** [comment]
Quite strange. Can't figure out why it can happen. Does regular Arduino IDE uploads successfully?

**Comment by defbug** [comment]
When I pass it through from host to guest windows vm. I can't still upload with the ide. But on a machine with windows i can upload without fail.

**Comment by nkrkv** [comment]
So it's not `ino` bug but a general problem with port forwarding?

**Comment by defbug** [comment]
I think so too. But why would it upload the sketch that comes with inotools?.. That is the thing I'm very curious about.

**Comment by Kernald** [comment]
The only difference I can spot is the firmware size. Blink is 1076B, while yours is 1084B. Maybe try to upload the blink with the Arduino IDE, and write a smaller program (less than 1076B) and try to upload it. If both works, maybe your serial port is reset every Xms which is enough to let 1076B pass but not 1084, or an overflow somewhere, …

**Comment by nkrkv** [comment]
Not related to `ino` in a nutshell
