### ISSUE TITLE
Packaging for Fedora

### ISSUE THREAD

**Issue by hroncok** [amperka/ino#62]
Hi,
I'm packaging ino for Fedora and here are two things that I have to solve.

There is a **MIT-LICENSE.txt** in this Git repository, but it is not in the tarball. However, the **README.rst** in the tarball references it. Could you please release a tarball with this license file?

The second thing is, that rpmlint (a tool, that checks if RPM package is OK) complains about empty and hidden files:

```
ino.noarch: W: hidden-file-or-dir /usr/lib/python2.7/site-packages/ino/templates/blink/lib/.holder
ino.noarch: E: zero-length /usr/lib/python2.7/site-packages/ino/templates/blink/lib/.holder
ino.noarch: W: hidden-file-or-dir /usr/lib/python2.7/site-packages/ino/templates/empty/lib/.holder
ino.noarch: E: zero-length /usr/lib/python2.7/site-packages/ino/templates/empty/lib/.holder
```

Could you please tell me, whether the empty hidden files are necessary? The best thing you can do is to answer to the following questions:
- If I delete those empty hidden files, would it break ino?
  - If it would, would adding content to those files break ino too? E.g. `echo foo > templates/blink/lib/.holder` 

Thanks a lot.

**Comment by nkrkv** [comment]
Hello! Great to hear that you're going to pack it for Fedora.

Here are answers:

1) Done
2) Will not break in either case

**Comment by hroncok** [comment]
Thanks

**Comment by hroncok** [comment]
ino package was approved and will be available as an update for Fedora 17 and Fedora 18 soon.

https://bugzilla.redhat.com/show_bug.cgi?id=904841

**Comment by nkrkv** [comment]
Weheee! :cocktail: 

Thank you!

**Comment by hroncok** [comment]
No problem :)
