### ISSUE TITLE
Unable to exit serial tool

### ISSUE THREAD

**Issue by chrisspen** [amperka/ino#67]
When using `ino serial` I'm unable to exit by the [documented](http://inotool.org/quickstart) method of "ctrl-a ctrl-x". Nothing happens when entering these key combinations. I've also tried the more Unix-standard ctrl-c, ctrl-q, and ctrl-z exit/suspend commands, but these are also ignored by `ino serial`.

I'm forced to kill the process, which is frustrating, especially since this needs to be done everytime before `ino upload` can begin uploading new firmware.

**Comment by nkrkv** [comment]
It is not ino issue. It just launches `picocom` with correct args. So the issue is in configuration of `picocom` on your machine. From manpage:

Commands  are given to picocom by first keying the "espace character" which by default is "C-a" (see "Options"
       below on how to change it), and then keying one for the function (command) characters shown here.

Make sure your escape character is C-a

**Comment by ndbroadbent** [comment]
Just to clarify for anyone else who finds this:

To quit picocom, you need to press `Ctrl-a`, then `Ctrl-q`.

**Comment by allgood38** [comment]
Haha, yes, note however, don't release the control key in between presses. That's what really made it difficult for me.

**Comment by joshuacox** [comment]
also of note the default C-a conflicts with screen's default, settings the options as noted above works i.e.

```
ino serial -- -e 'x'
```

**Comment by ch3ll0v3k** [comment]
Thx, helpfull

**Comment by ausinch** [comment]
Also if you use screen Ctrl-a conflicts.  The work around is easy:
Ctrl-a,a,Ctrl-x
