### ISSUE TITLE
Ino block when library don't have cpp file

### ISSUE THREAD

**Issue by hugokernel** [amperka/ino#69]
Hi,

I use an Arduino library (https://github.com/hugokernel/Oled4D) without cpp file and build block when scanning this library.

...
Scanning dependencies of Oled4D

And nothing happens...

**Comment by Kernald** [comment]
Hi, I have the same issue, see #56. A workaround is to add a simple CPP file to the library, doing nothing more than including a header.

**Comment by nkrkv** [comment]
Fixed in 0.3.6
