### ISSUE TITLE
Can't Build on a Headless Raspberry Pi

### ISSUE THREAD

**Issue by cbeach** [amperka/ino#77]
I'm trying to get a data logging server up and running using a Raspberry Pi running Raspbian and an Arduino.  I've been trying to build the blink template project, but the build of avr-gcc that the Arduino IDE ships with does not run on the ARM architecture.  I tried to find the code so I can compile the binaries myself, but no go.  It looks link Arduino distributes pre-compiled gcc binaries in a tarball.  That makes sense for 99.99% of use cases, but doesn't help me very much :)

Is there a way to make ino use the system's native avr-gcc?  If not, it might be nice a feature to have for some weird edge cases. (like mine)

**Comment by sys49152** [comment]
Hi
Install from Raspbian repositories.
Do something like:

sudo apt-get update
sudo apt-get install arduino

that should give you the necessary environment.

**Comment by natcl** [comment]
I can confirm that it this works, been doing this for a few weeks now with a Raspberry Pi and a Mega.

**Comment by cbeach** [comment]
Yep,  That worked.
