### ISSUE TITLE
weird error on mac, during quick start guide

### ISSUE THREAD

**Issue by ryho** [amperka/ino#80]
I'm on OS X, up to date, and I installed using the command

```
make install PREFIX=/usr
```

I went to the quick start guide, ran everything as it said, and it gives me this indiscernible error:

```
$ ino upload
Searching for stty ... /bin/stty
Searching for avrdude ... /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avrdude
Searching for avrdude.conf ... /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/etc/avrdude.conf
Guessing serial port ... /dev/tty.usbmodemfd111
avrdude: stk500_getsync(): not in sync: resp=0x24

avrdude done.  Thank you.
```

**Comment by nkrkv** [comment]
Hello, looks like ino guessed serial port incorrectly. Could you provide it explicitly on command line with `-p` switch?

**Comment by ryho** [comment]
I compared the serial port chosen by ino with the one in the Tools menu of the Arduino IDE, and ino correctly switches between the serials, /dev/tty.usbmodemfa131 and /dev/tty.usbmodemfd111, when I switch USB ports. (If you are on Linux, I believe the format for serials on OS X is different; this is correct for my Mac.)

More details:
I'm using an Arduino Micro, a MacBook Air 4,1, OS X Mountain Lion, everything is up to date. I just downloaded the code again and reinstalled. The real Arduino IDE uploads this sketch properly. I gave the Arduino a blank sketch using the IDE as a precaution since the sketch I already had on it was doing a lot of output on Serial.

Also my computer has always had weirdness about uploading to Arduinos. About 50% of the time (maybe more) the Arduino IDE gives me some meaningless error in the black text box while uploading. Even when it gives me this error, the sketch actually uploads to the Arduino and it works as expected. This is so annoying since every time I upload, I have to read the error to see if it is a real error, or just the dumb one that often happens. So, is there a way to force this thing to keep uploading even if there is an error? It might be complaining about whatever Arduino IDE complains about, even though when I run ino, it never uploads without an error, or gives an error while actually accomplishing the upload.

I'm getting different errors today and I never saw the exact error I posted above (`resp=0x24`), so I'm posting the new errors. I always get the following the first time after reconnecting or resetting the Arduino:

```
$ ino upload
Guessing serial port ... /dev/tty.usbmodemfd111
avrdude: stk500_getsync(): not in sync: resp=0x3f

avrdude done.  Thank you.
```

Then it usually shows one of the following:

```
$ ino upload
Guessing serial port ... /dev/tty.usbmodemfd111
avrdude: ser_recv(): read error: Device not configured

$ ino upload
Guessing serial port ... FAILED
No device matching following was found: 
  - /dev/tty.usbmodem*
  - /dev/tty.usbserial*
```

Then it shows this message on every run until I  reset  or disconnect/reconnect the board:

```
$ ino upload
Guessing serial port ... /dev/tty.usbmodemfd111
avrdude: stk500_recv(): programmer is not responding

avrdude done.  Thank you.
```

Here is the error I usually get from the Arduino IDE, in case you know what it means:

```
processing.app.SerialException: Error touching serial port '/dev/tty.usbmodemfd111'.
    at processing.app.Serial.touchPort(Serial.java:123)
    at processing.app.debug.AvrdudeUploader.uploadViaBootloader(AvrdudeUploader.java:201)
    at processing.app.debug.AvrdudeUploader.uploadUsingPreferences(AvrdudeUploader.java:67)
    at processing.app.Sketch.upload(Sketch.java:1671)
    at processing.app.Sketch.exportApplet(Sketch.java:1627)
    at processing.app.Sketch.exportApplet(Sketch.java:1599)
    at processing.app.Editor$DefaultExportHandler.run(Editor.java:2380)
    at java.lang.Thread.run(Thread.java:680)
Caused by: gnu.io.UnsupportedCommOperationException: Invalid Parameter
    at gnu.io.RXTXPort.setSerialPortParams(RXTXPort.java:171)
    at processing.app.Serial.touchPort(Serial.java:113)
    ... 7 more
```

**Comment by nkrkv** [comment]
I can't guess what could be a reason. Maybe file mode? Try `chmod 777 /dev/tty.usbmodemfd111`

**Comment by lukebayes** [comment]
I was seeing this exact same behavior. Uploads worked (intermittently) using the IDE, but never worked from ino with this same series of errors.

I'm on a MacBook Air and uploading to an Arduino Micro.

Turned out, I need to specify the micro model like:

```
ino upload -m micro
```

**Comment by nkrkv** [comment]
The deal is in `-m` flag. So it looks like there is no problem actually. If it still persist feel free to reopen the issue.
