### ISSUE TITLE
Feature request: Ability to specify escape character to ino serial

### ISSUE THREAD

**Issue by joequery** [amperka/ino#81]
I use C-a for GNU screen, and I'd like the ability to specify the escape character to use for the ino serial.

From the picocom man page:

```
       --esacpe | -e
          Defines  the  character  that  will  make  picocom enter command-mode (see description
          above). If 'x' is given, then C-x will make picocom enter command mode.

          (Default: 'a')
```

I may tackle this myself if I can find the time.

I love this tool, by the way :)

**Comment by nkrkv** [comment]
Starting from 0.3.6 you can pass it as an extra arg, after `--`
