### ISSUE TITLE
Add interactive shell to ino tools

### ISSUE THREAD

**Issue by endorama** [amperka/ino#91]
Hello, I'm happily using Ino to develop on Arduino using Ubuntu!

This is a feature request, which could be useful in lot of test cases in which you need to test sensors input/output or monitor particular conditions.

Could be possible to add an **interactive shell** to ino, so that you can execute arduino code from console, perform action on pins and so on?

A kind of Serial communication that can accept input command and run them onto the arduino board!

Thanks for your efforts! :)

**Comment by nkrkv** [comment]
Interesting idea but I'm not sure it should be in core. Looks like a separate program that could be based on `ino`
