### ISSUE TITLE
Problem adding include file in lib folder

### ISSUE THREAD

**Issue by uneame** [amperka/ino#94]
Hello,

I follow the quickstart and everything went smoothly, now I'm trying to add an include file (containing only define) and at build time inotools output that:

user@computer:~/sketchbook/new_app$ ino build
src/sketch.ino
Scanning dependencies of src
src/sketch.cpp
src/sketch.ino:1:24: fatal error: app.h : Aucun fichier ou dossier de ce type
compilation terminated. // aka no such file
make: **\* [.build/uno/src/sketch.o] Erreur 1
Make failed with code 2

the file app.h is located in ~/sketchbook/new_app/lib and don't work either if i put it in src.

Have you any clue ?

Thancks.

**Comment by nkrkv** [comment]
You should put `app.h` in a subdirectory of a concrete library directory. I.e:

`~sketchbook/new_app/lib/mylibrary/app.h`
