### ISSUE TITLE
ino doesn't look in /etc/avrdude/ for avrdude.conf

### ISSUE THREAD

**Issue by scottchiefbaker** [amperka/ino#98]
On Fedora, the avrdude.conf is stored in /etc/avrdude. This causes ino upload to error out:

bakers@snikt(/tmp/test)
:ls /etc/avrdude/avrdude.conf -l
-rw-r--r-- 1 root root 550242 Jul 18  2012 /etc/avrdude/avrdude.conf

bakers@snikt(/tmp/test)
:ino upload
Searching for avrdude.conf ... FAILED
avrdude.conf not found. Searched in following places: 
- /usr/local/share/arduino/hardware/tools
- /usr/share/arduino/hardware/tools

Can it check that directory, and maybe optionaly ~/.avrdude.conf as well?

**Comment by nkrkv** [comment]
Fixed in 0.3.6
